apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lwwebflaskdeploy3
  name: lwwebflaskdeploy3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: lwwebflaskdeploy3
  type: LoadBalancer
status:
  loadBalancer: {}
